spring:
  application:
    name: autoDepot
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:autodepot}
    username: ${DB_USER:autodepot}
    password: ${DB_PASSWORD:autodepot}
    driverClassName: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8080}
