spring:
  application:
    name: autoDepot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:55432}/${DB_NAME:autodepot}
    username: ${DB_USER:autodepot}
    password: ${DB_PASSWORD:autodepot}
    driverClassName: org.postgresql.Driver

server:
  port: 8080
